---
- name: Kubernetes Setup
  hosts: kubernetes
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add docker gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add docker repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable
        state: present

    - name: Install docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: Ensure Docker service is enabled and started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true


    - name: Add Kubernetes GPG-Key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Kubernetes-Repository zu den Quellen hinzufügen
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /'
        create: yes

    - name: Apt update
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 0

    - name: Install kubelet
      ansible.builtin.apt:
        name: 
          - kubelet
          - kubeadm
          - kubectl
        
        state: present

    - name: Kubernetes Version hold 1.33
      shell: apt-mark hold kubelet kubeadm kubectl
      become: true
        
    - name: Systemd-Service Kubelet
      ansible.builtin.systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Check Containerd Config File
      stat:
        path: /etc/containerd/config.toml
      register: containerd_config

    - name: Containerd File erstellen wenn noch nicht vorhanden.
      shell: containerd config default | sudo tee /etc/containerd/config.toml

    - name: SystemdCgroup anpassen = false to true
      replace:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup\s*=\s*false'
        replace: '\1SystemdCgroup = true'

    - name: Containerd restart
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Swap off
      shell: swapoff -a
      become: true

    - name: Remove Swap from Fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].* swap .*)$'
        replace: '# \1'
